### ISSUE TITLE
# 12 Программа для проверки, что в десятичной записи числа нет одинаковых цифр

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#12]
Напишите программу, которая принимает трехзначное число, и проверяет, что в десятичной записи введенного числа нет одинаковых цифр, противном случае просит ввести трехзначное число

**Comment by Akyless** [comment]
Cделала задание (не одинаковые цифры)
ExerciseS12.java
Commit ID:  6502fffd

**Comment by Almaz-KG** [comment]
Reviewed & Closed
