### ISSUE TITLE
# 17 Счастливый билет

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#17]
Напишите программу, которая принимает от пользователя шестизначное число, и проверяет является ли введенное число “Счастливым”. Счастливым считается шестизначное число, в котором сумма первых трёх цифр совпадает с суммой трёх последних.

**Comment by Akyless** [comment]
Cделала задание 17 (lucky ticket)
ExerciseS17.java
Commit ID:  25ad2ad7

**Comment by Almaz-KG** [comment]
Reviewed and Closed
