### ISSUE TITLE
## 20 Числа Фибоначчи

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#20]
Числа Фибоначчи

Напишите программу, которая запрашивает у пользователя число (индекс в последовательности рядя Фибоначчи), и выводит значение ряда в этом индексе.

Ряд Фибоначчи выглядит следующим образом
1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, ...

Если пользователь ввел число 7, то программа должна вывести текст:
"В ряде Фибоначчи на 7 месте стоит число: 13"

Или если пользователь ввел число 10, то программа должна вывести текст:
"В ряде Фибоначчи на 10 месте стоит число: 55"

**Comment by Akyless** [comment]
Задание 20 (число Фибоначчи)
ExrciseS20.java
Commit ID:  69257bc6

**Comment by Almaz-KG** [comment]
Good job Almaz)

Reviewed and Closed
