### ISSUE TITLE
# 21 Наибольшее и наименьшее из трех целых чисел

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#21]
Вводятся три целых числа. Определить какое из них наибольшее и наименьшее, вывести их на экран

**Comment by Akyless** [comment]
Сделала задание 21
Exercise3.java
Commit ID: 7b5e0aec

**Comment by Akyless** [comment]
Отредактировала задание
Exercise3.java
Commit ID: b35960c6

**Comment by Almaz-KG** [comment]
Reviewed & Closed

Пока так сойдет, в будущем можно будет этот код отрефакторить намного проще
