### ISSUE TITLE
# 23 Проверить делится ли первое число на второе

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#23]
Вводятся два целых числа. Проверить делится ли первое на второе. Если первое число нацело делится на второе, то вывести сообщение об этом.

Иначе вывести сообщение о том, что первое число не делится на второе, найти остаток от деления и также вывести его.

В конце программы найти частное от деления чисел и вывести его.

**Comment by Akyless** [comment]
Сделала задание
Exercise5.java
Commit ID : 74d61484
