### ISSUE TITLE
# 24 Конвертер байты в килобайты и наоборот

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#24]
Задача
Перевести число, введенное пользователем, в байты или килобайты в зависимости от его выбора.

Пояснение к задаче и алгоритм решения
В данной задаче пользователь должен ввести два значения: само число и как-либо указать, во что он хочет его перевести (в байты или килобайты). Пусть выбор способа перевода указывается с помощью одного из двух символов. Например, если пользователь введет букву "b", то число будет переводиться в байты, а если букву "k", то в килобайты. Тогда алгоритм решения задачи будет следующим:

Ввести число.
Указать направление перевода.
Если выбран перевод в байты, то надо умножить число на 1024.
Если выбран перевод в килобайты, то надо разделить число на 1024.

В данной задаче нельзя оставлять второй случай без проверки, т.е. использовать исключительно ветку else, т.к. пользователь может ввести что угодно. Поэтому надо использовать либо две отдельные ветки if, либо вложенную в else вторую проверку через if. С точки зрения наиболее оптимального кода второй вариант предпочтительнее, т.к. в случае срабатывания первого if второй проверяться не будет.

**Comment by Akyless** [comment]
Сделала задание 
Exercise6.java
Commit ID: 4bb2a8eb

**Comment by Almaz-KG** [comment]
Reviewed & Closed
