### ISSUE TITLE
# 25 Определение английской буквы по ASCII коду

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#25]
Задача
Вводится целое число, обозначающее код символа по таблице ASCII. Определить, это код английской буквы или какой-либо иной символ.

Пояснение к задаче и алгоритм решения
В таблице ASCII символы букв идут по порядку - от "A" до "Z", далее через несколько небуквенных символов от "a" до "z".

Задача сводится к тому, что надо сравнить код-число, введенное пользователем, с кодами первых и последних букв алфавита. Если код принадлежит этим диапазонам, значит это код буквы, если нет - то небуквенный символ.

```
Введите код: 37
Это не буква, а символ %

Введите код: 48
Это не буква, а символ 0

Введите код: 64
Это не буква, а символ @

Введите код: 66
Это буква B
```

**Comment by Akyless** [comment]
Сделала задание
Exercise10.java
Commit ID: 63e06ba1

**Comment by Akyless** [comment]
Сделала задание
Exercise10.java
Commit ID: e6716472

**Comment by Almaz-KG** [comment]
Reviewed & Closed
