### ISSUE TITLE
# 27 Ряд натуральных чисел от минимума до максимума с заданным шагом

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#27]
Вывести на экран ряд натуральных чисел от минимума до максимума с шагом. Например, если минимум 10, максимум 35, шаг 5, то вывод должен быть таким: 10 15 20 25 30 35. Минимум, максимум и шаг указываются пользователем (считываются с клавиатуры).

**Comment by Akyless** [comment]
Сделала задание 
ExerciseS27.java
Commit ID: df38207c

**Comment by Almaz-KG** [comment]
Reviewed & Closed
