### ISSUE TITLE
# 28 Найти наибольшую цифру натурального числа 

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#28]
Задача
С клавиатуры вводится натуральное число. Найти его наибольшую цифру.

Например, введено число 764580. Наибольшая цифра в нем 8.

**Comment by Akyless** [comment]
Cделала задание (наибольшая цифра в числе)
ExerciseS28.java
Commit ID: c1febfbc

**Comment by Akyless** [comment]
Удалила лишнюю переменную (c  Math.abs())
ExerciseS28.java
Commit ID: 38335c3b

**Comment by Almaz-KG** [comment]
Reviewed and Closed
