### ISSUE TITLE
# 29 Вывести на экран таблицу умножения

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#29]
Вывести на экран таблицу умножения (от 1 до 9).
```
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
...
9 x 8 = 72
9 x 9 = 81
```

**Comment by Akyless** [comment]
Выполнила задание 29
ExerciseS29.java
Commit ID: 1f873a8e

**Comment by Almaz-KG** [comment]
Оставь оба варианта, в разных файлах, примерно так:
- Exercise29For.java
- Exercise29While.java

**Comment by Akyless** [comment]
Сделала задание 29 (таблица умножения)
Exercise29For.java
Exercise29While.java
Commit ID:  2e6e504f

**Comment by Almaz-KG** [comment]
Reviewed & Closed
