### ISSUE TITLE
# 38 Сумма четных положительных элементов в массиве

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#38]
Задача

В массиве, содержащем положительные и отрицательные целые числа, вычислить сумму четных положительных элементов.

**Comment by Akyless** [comment]
Cделала задание 38 (Сумма четных '+' элементов в массиве)
ExerciseS38.java
Commit ID:  bd7974ab

**Comment by Akyless** [comment]
Внесла изменения в код (сумма четных '+' элементов в массиве)
ExerciseS38.java
Commit ID:  7f713fb8

**Comment by Almaz-KG** [comment]
Оставил комментарии - исправь их

**Comment by Akyless** [comment]
Исправила задание (сумма четных '+' эл в массиве)
ExerciseS38.java
Commit ID:  051e84a7

**Comment by Almaz-KG** [comment]
Reviewed and Closed
