### ISSUE TITLE
# 40 Площадь круга, прямоугольника или треугольника

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#40]
Задача

В зависимости от выбора пользователя вычислить площадь круга, прямоугольника или треугольника. Для вычисления площади каждой фигуры должна быть написана отдельная функция.

```
Круг(c), прямоугольник(r) или треугольник(t): c
Радиус: 2
Площадь: 12.57


Круг(c), прямоугольник(r) или треугольник(t): r
Длина и ширина: 3.85 12.55
Площадь: 48.32


Круг(c), прямоугольник(r) или треугольник(t): t
Стороны: 3 4 6.5
Площадь: 4.17
```

**Comment by Akyless** [comment]
Сделала задание 
Exercise9.java
Commit ID: 3a742122

**Comment by Almaz-KG** [comment]
Reviewed & Closed
