### ISSUE TITLE
# 48 Названия месяцев

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#48]
Ввести число от 1 до 12. 

Вывести на консоль название месяца, соответствующего данному числу используя оператор switch (Осуществить проверку корректности ввода чисел).

**Comment by Akyless** [comment]
Сделала задание (название месяца)
ExerciseS48IFelse.java
Commit ID:  96c80bfa

**Comment by Akyless** [comment]
Cделала задание (switch- название месяца)
ExerciseS48switch.java
Commit ID:  fb70927d

**Comment by Almaz-KG** [comment]
Reviewed and Closed
