### ISSUE TITLE
# 07 Игра "Угадай число"

### ISSUE THREAD

**Issue by Almaz-KG** [Akyless/LearningJava#7]
Напишите простую игру основанную на угадывании числа

Пользователь должен угадать загаданное компьютером число (от 0 до 100), введя его в консоль.  На каждую игру, компьютер должен загадывать новое число.  

Если пользователь угадал - программа должна вывести «Молодец!» и игра должна закончится, если нет, то пользователь продолжит вводить числа, пока не отгадает. 

Вывести «Мало»- если пользователь ввел число меньше загаданной, «Много»- если пользователь ввел число больше загаданной

**Comment by Akyless** [comment]
Cделала задание (Угадай число)
ExerciseS07.java
Commit ID:  8daea9d2

**Comment by Almaz-KG** [comment]
Reviewed & Closed
